/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package mm1


import mm1.model.Configuration
import mm1.model.EventGenerator
import mm1.model.EventList
import mm1.model.EventType
import mm1.simulator.Simulator

class App {
    static String getGreeting() {
        return 'MM1 simulator starting...'
    }

    Properties readProperties(String fileName) {
        Properties properties = new Properties()
        getClass().getResource(fileName).withInputStream {
            properties.load(it)
        }

        properties.each { println String.format("%-10s -> %-10s", it.key, it.value) }

        return properties
    }

    static void main(String[] args) {
        println greeting

        Properties properties = new App().readProperties('/user-input.properties')

        Configuration config = new Configuration(properties)

        EventGenerator generator = new EventGenerator(config)

        EventList eventList = new EventList()

        generator.generate(eventList)

        println(eventList.toString())
        println(eventList.eventList.size().toString())
        println(eventList.eventList.findAll {it.type == EventType.MESSAGE}.size().toString())

        Simulator simulation = new Simulator(config)

        simulation.simulate(eventList)
    }
}
