/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package mm1

import mm1.simulator.Simulator

class App {
    String getGreeting() {
        return 'MM1 simulator starting...'
    }

    Properties readProperties(String fileName) {
        Properties properties = new Properties()
        File propertiesFile = new File(getClass().getResource(fileName).toURI())
        propertiesFile.withInputStream {
            properties.load(it)
        }

        properties.each { println "$it.key -> $it.value" }

        return properties
    }

    static void main(String[] args) {
        println new App().greeting
        // Read properties from main/groovy/resources/user-input.properties
        Properties properties = new App().readProperties('/user-input.properties')

        // Run MM1 simulation
        Simulator simulation = new Simulator(
                (Double) properties.lambda,
                (Double) properties.mu,
                properties.probes as Integer,
                properties.seed as Integer
        )
        simulation.simulate()

        println "Results:"
        println "Events in system:" + simulation.eventsInSystem
        println "Events in queue:" + simulation.eventsInQueue
    }
}
